name = "fx4chan"
main = "indexCloudFlare.js"
compatibility_date = "2024-01-01"

[[env.production.routes]]
pattern = "fx4chan.choovershrimp.workers.dev/*"
zone_name = "fx4chan.choovershrimp.workers.dev"